# Generated by Django 2.2 on 2019-04-09 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('amount', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associatedStaff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('positions', models.ManyToManyField(related_name='orders', to='chefsbookApi.OrderPosition')),
                ('table', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chefsbookApi.Table')),
            ],
        ),
    ]
